# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a63d9de83e7e6e30493193ef88813b8932a0f939cb921785dd7443907b9d9da0ab8d5094ce485eadcffdc41f29e8c93bb489d707a40a27473c05a74864cb5199

test:
  secret_key_base: 610bc4bdd0cf0ab1c2750160972bfe1cbeaeb62696817e1ec16f9fe8ed04d0d0d82cd16ba1580409712834a0372c661b3ca6da2f14df2044877e4f891082bdfb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
