# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 468ddeb04c012ac4579ee4b89ca8bd03628e5cf322fa51f37f9059b4430a8a18d4dfe7ff7cb194ae4b254a65541ac5d1d9d35e799cc4e8f7c4564195eeddb327

test:
  secret_key_base: 6c6ed09a4d1d2e450caddd1f929bc68950c56494267b127ac433f192079e8179237beff0a6052dccbcd1be52eb8de7a0a082edce139dc00636b8d39c9ed54da4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
